@startuml
start

:Старуха формирует запрос;
:Старик передает запрос Рыбке;

if (Лимит не превышен?) then (да)
    :Рыбка исполняет желание;
    :Повышение амбиций;
    repeat
        :Новый более сложный запрос;
        :Передача через Старика;
    repeat while (Лимит не превышен?)
else (нет)
    :Сброс системы;
endif

stop
@enduml
